### ISSUE TITLE
这是Archlinux-cn自动邀请bot吗

### ISSUE THREAD

**Issue by kitech** [quininer/groupbot#1]
这个bot的profile呢？我想启一个服务。

**Comment by quininer** [comment]
是，昨天我的 VPS 网络维护了。我重启一下，把你设置成 master 好了。

在 2016年05月19日 12:29, yatsen1 写道:

**Comment by quininer** [comment]
bot 上线之后，你手动邀请 bot 进群就可以了。

在 2016年05月19日 12:29, yatsen1 写道:

**Comment by kitech** [comment]
还有master?
我再看看怎么用。

**Comment by kitech** [comment]
不过你在维护的话我就不急了，先看代码。
